mozilla/burnham

docker-compose.yml, src/burnham/cli.py, src/burnham/config/metrics.yaml
=> Set test information in Glean

application/src/burnham/cli.py
=> Update telemetry CLI option and enable by default

application/README.md, application/setup.py, application/src/burnham/__init__.py
=> Switch to Calendar Versioning

application/src/burnham/config/metrics.yaml, application/src/burnham/config/pings.yaml
=> Update data review url

.circleci/config.yml
=> Create Circle CI config for running code checks

application/setup.py, fake-data-platform/app.py
=> Decompress pings on fake data platform

.circleci/config.yml
Hi @jklukas! 👋 
I'd appreciate your review on this update to our Circle CI config, which adds a new job for building and pushing the Docker image for running queries and comparing results to GCP. Do we need to provision another GCP project before we can merge this?
Resolve #27
=> Build and push BigQuery image 📦

application/setup.py
=> Upgrade Glean SDK to version 31.2.1 📦

bigquery/tests/conftest.py
=> Refactor tests to accept base64 encoded scenarios

application/Dockerfile
=> Resolve setuptools issue 📦

application/README.md
=> Document how to install custom Glean SDK dist 📝

README.md
Hi folks! 
This pull-request adds documentation for the burnham test suite to the repository README.
Please let me know your thoughts!
Resolve #31
=> Write documentation for the burnham test suite 📝

README.md
=> Document project theme on README

bigquery/tests/conftest.py, bigquery/tests/plugins/store_results_in_bigquery.py
=> Store results in BigQuery

bigquery/tests/plugins/store_results_in_bigquery.py
See https://github.com/mozilla/burnham/pull/62#pullrequestreview-475494446
=> Fix test report encoding issue in burnham-bigquery 🤖

bigquery/tests/plugins/store_results_in_bigquery.py
Follow-up pull-request for #63
=> Encode table rows to bytesIO when loading to BigQuery 🤖

bigquery/tests/plugins/store_results_in_bigquery.py
Follow-up pull-request for #64
=> Specify LoadJob source format as JSON 🤖

application/setup.py, application/src/burnham/cli.py, docker-compose.yml
=> Unpin Glean SDK version for burnham application 📦

application/src/burnham/cli.py
=> Specify Glean data_dir as required by v32.0.0 📦

application/src/burnham/cli.py, application/src/burnham/config/metrics.yaml, application/src/burnham/config/pings.yaml, application/src/burnham/missions.py
=> Add new custom pings 🤖

bigquery/tests/conftest.py
=> Add burnham-bigquery CLI option for start-timestamp

labels.toml
I updated the GitHub issues labels. This pull-request brings the labels.toml file in sync with it.
Resolve #79
=> Update labels file 📝

README.md, application/README.md, bigquery/README.md
=> Update documentation 📝

.github/CODEOWNERS
=> Set up GitHub code owners 📋

.circleci/config.yml, application/pyproject.toml, application/tox.ini
=> Set up code coverage report 🤖

.circleci/config.yml, application/dev-requirements.in, application/dev-requirements.txt, application/src/burnham/cli.py, application/src/burnham/experiments.py, application/tests/test_cli.py, application/tests/test_missions.py, application/tox.ini
This pull-request adds a code check that verifies burnham application code is formatted using [black][black].
[black]: https://pypi.org/project/black/
See #93
=> Add black to code checks 🤖

application/tox.ini
=> Update burnham installation in tox 🤖

application/tox.ini
=> Run pip check in tox 🤖

application/setup.py, application/src/burnham/__init__.py, application/src/burnham/cli.py, application/src/burnham/config/metrics.yaml, application/src/burnham/missions.py, application/tests/conftest.py, application/tests/test_cli.py, application/tests/test_missions.py
=> Develop deletion-request ping test 👩‍🚀

application/requirements.txt
The new release includes a bugfix for the upload timeouts.
=> Upgrade glean-sdk 📦

.github/CODEOWNERS
=> Add GitHub code owners file 📋

application/tox.ini
=> Add --diff CLI flag to black in tox 🤖

application/docs/usage.md, application/src/burnham/cli.py, application/src/burnham/config/metrics.yaml, application/tests/test_cli.py
=> Add Airflow task ID metric to burnham CLI 🚀

application/README.md
Missed to change this section when reorganizing the docs in #385.
=> Correct development documentation 📝

application/src/burnham/cli.py, application/tests/test_cli.py
=> Restore airflow_task_id after disable upload 

.circleci/config.yml, application/Dockerfile, application/mypy.ini, application/setup.py, application/tox.ini, bigquery/Dockerfile, bigquery/requirements.txt
Updates the burnham application to python 3.10(.4)
=> Fixes #413: Update python version.
